name: Trivy security scan
on:
  schedule:
    - cron: '40 6 * * *'
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

# TODO Are: Slette alle disse, ev. flytte inn i hver job?
#permissions:
  #  contents: read
  #  id-token: write # TODO Are: Unødvenidg og kan slettes?
  # TODO ARE: Hva av det følgende er egentlig nødvendig?
#  actions: read
#  contents: write
#  security-events: write
#  packages: write
#  id-token: write

jobs:
  call-build-and-publish:
    uses: ./.github/workflows/build-and-publish.yaml
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  call-trivy-security-scan:
    needs: call-build-and-publish
    uses: navikt/toi-github-actions-workflows/.github/workflows/trivy-security-scan.yaml@main # TODO Are: Droppe @main?
    with:
      image: ${{ needs.call-build-and-publish.outputs.image }}
    permissions:
      id-token: write
      security-events: write
    secrets: inherit
