name: Trivy security scan
on:
  schedule:
    - cron: '40 5 * * *'
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  call-build-and-publish:
    uses: navikt/toi-github-actions-workflows/.github/workflows/build-java-gradlew.yaml@main
    permissions:
      contents: read
      id-token: write
    secrets: inherit

  call-trivy-security-scan:
    needs: call-build-and-publish
    uses: navikt/toi-github-actions-workflows/.github/workflows/trivy-security-scan.yaml@main
    with:
      image: ${{ needs.call-build-and-publish.outputs.image }}
    permissions:
      id-token: write
      security-events: write
    secrets: inherit
