name: Trivy security scan
on:
  schedule:
    - cron: '40 5 * * *'
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  call-build-and-trivy:
    uses: navikt/toi-github-actions-workflows/.github/workflows/build-and-trivy.yaml@main
    with:
      java-version: '21'
    permissions:
      contents: read
      id-token: write
      security-events: write
    secrets: inherit
