name: Security scan
on:
  schedule:
    - cron: '40 6 * * *'
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read
  id-token: write # TODO Are: Unødvenidg og kan slettes?

jobs:
  call-build-and-publish:
    uses: ./.github/workflows/build-and-publish.yaml
    secrets: inherit

  trivy:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Push Trivy/Sarif to Github Security
      packages: read # TODO Are: Unødvenidg og kan slettes?
    needs: call-build-and-publish
    steps:
#      - run: touch me # TODO Are: name istedenfor run?
#      - uses: nais/login@v0
#        with:
#          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
#          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
#          team: toi # TODO Are: Hente fra variabel?

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ needs.call-build-and-publish.outputs.image }}'
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy.sarif'
